### ISSUE TITLE
Более качественный хайлайтер кода урки

### ISSUE THREAD

**Issue by fireton** [devapromix-ifiction/urq-edit#11]
Я когда-то начинал писать редактор кода урки (в диалекте фурки). И понял, что генерёный хайлайтер довольно фиговый. У уркл очень нестандартный синтаксис. Нужно различать, например, `IF` в коде и `IF` после `PLN`, все эти вещи. Плюс объединение через `&`. Плюс подстановки.

В общем, я написал свой хайлайтер, руками, он все эти вещи отслеживает. Он довольно умный. :)

Ты глянь, может он пригодится. 
[urqhighlighter.zip](https://github.com/devapromix-ifiction/urq-edit/files/2235260/urqhighlighter.zip)

Я не сделал настройку цветов. Они по умолчанию такие, как мне нравится в дельфи. :)
Но это несложно поправить же.

**Comment by devapromix** [comment]
Забавно :) Спасибо огромное.

**Comment by fireton** [comment]
Забыл, оно ещё и служебные переменные подсвечивает. Включая переменные декораторов.

**Comment by fireton** [comment]
Вообще, SynEdit довольно мощная штука. Там можно реализовать подчёркивание красным для несуществующих локаций, например. Т.е. проверять код на лету. Или выводить список уже существующих локаций по Ctrl+Enter после btn... Много чего можно придумать. Если допилишь до релиза, я, может, тоже смогу что-то прикрутить и кину PR. 

К слову, ты какую версию Дельфи используешь?

**Comment by devapromix** [comment]
Дельфи XE 10.2 Токио.

**Comment by devapromix** [comment]
Я по хайлайтеру создал отдельный репо, так как использую его еще в одном проекте https://github.com/devapromix-delphi/SynEditURQL

**Comment by devapromix** [comment]
Готово. Хайлайтер "впилен" в редактор. Спасибо, Fireton :+1:
